version: '3.7'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./my-db:/var/lib/mysql
    restart: always
    ports:
      - 33060:3306
    networks:
      - clipmenet
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clipme
  
  # clipme:
  #   container_name: clipme
  #   restart: always
  #   build: ./backCompleteJava
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - clipmenet
  #   depends_on:
  #     - db
  #   links:
  #     - db
  
  clipping:
    container_name: clipping
    restart: always
    build: ./clipping
    depends_on:
      - db
    links:
      - db
    ports:
      - 8082:8080
    networks:
      - clipmenet

  user:
    container_name: user
    restart: always
    build: ./user
    depends_on:
      - db
    links:
      - db
    ports:
      - 8083:8080
    networks:
      - clipmenet
  
  facade:
    container_name: facade-clipme
    restart: always
    build: ./facade
    depends_on:
      # - clipme
      - clipping
      - user
    links:
      # - clipme
      - clipping
      - user
    ports:
      - "8080:8081"
    networks:
      - clipmenet

  front:
    container_name: front-clipme
    restart: always
    build: ../../frontEnd
    depends_on:
      - facade
    ports:
      - "4200:4200"
    networks:
      - clipmenet

networks:
  clipmenet:
    driver: bridge
